### ISSUE TITLE
[Proposal] Sort snippets by number of comments and total points

### ISSUE THREAD

**Issue by alex-netquity** [florianbeer/vimrcfu#10]
I have been working on adding sorting functionality to the Browse Snippets page. It works as follows:

* The Browse Snippets page is sorted by ID as is the current convention
* A new Statistics menu is added to the right side. The items in that menu are as follows, with the first three being links, and the last three just displaying a count (as is presently displayed on the index page):
  * By Points
  * By Comments
  * By Date
  * Snippets
  * Comments
  * Users
* The links in the Statistics menu take you to a page with the same formatting as Browse Snippets, but therein the snippets are sorted accordingly
  * There are 10 snippets shown per page
  * Pagination is supported
    * Laravel 4.x does not efficiently support combining `groupBy` and `paginate`. For this reason implemented the sorting using manual pagination. See http://laravel.com/docs/4.2/pagination#usage

I think the new Statistics menu could replace the old entirely. Most people probably don't need an option to see `Top Snippet` as well as a list of all snippets in order of most votes. Same thinking applies to the `Most Comments`. I didn't make this change, though. Right now there are two different menus (the new and the old), depending on whether the user is on the home page or on the Browse Snippets pages.

**Comment by alex-netquity** [comment]
Here's the code if you want to review the content:
https://github.com/alex-netquity/vimrcfu/compare/florianbeer:dev...feature/sorting_snippets

**Comment by florianbeer** [comment]
I took a somewhat reduced approach now and introduced "Hot Snippets".
This is a list sorted by score and shows all Snippets with more than one points.

**Comment by alex-netquity** [comment]
Your approach does not include the Sort by Most Comments functionality that is part of my solution, but I suppose there could be a case for keeping things simple. 

Thanks for letting us view the hottest snippets!
