### ISSUE TITLE
Don't show "Post your first snippet" button when you have already posted

### ISSUE THREAD

**Issue by Kazark** [florianbeer/vimrcfu#11]
It doesn't make sense to show the "Post your first snippet" button:

![postyourfirstsnippetbutton](https://cloud.githubusercontent.com/assets/3661051/7306004/41b5af36-e9d0-11e4-856b-9628f3e968dd.png)

once you have already posted your first snippet (or many):

![alreadypostedseveral](https://cloud.githubusercontent.com/assets/3661051/7305999/3c50ee98-e9d0-11e4-96f3-fdcd3c088ba5.png)

**Comment by florianbeer** [comment]
Good idea!
The call to action button was one of the first design elements I put in and then never thought about it again. I've changed the wording in 98db710
