### ISSUE TITLE
OAuth Login Failed

### ISSUE THREAD

**Issue by zQueal** [florianbeer/vimrcfu#13]
Github login returns a white page with;

    int(-1)

**Comment by florianbeer** [comment]
Hi,
thanks for your report. I have noticed this a while ago but just don't have the time right now to fix it. You are very welcome to submit a pull request, preferably replacing the login system with something that's built into Laravel (e.g. [Socialite](https://github.com/laravel/socialite))

**Comment by florianbeer** [comment]
I dug deep and after about an hour of tracing through the source I found out it was an error in my session settings :(

Well, whatever...

**Vimrcfu** is **back up** and **operational**! 👍
